/// Common Border Radius
const BORDER_RADIUS_NORMAL = 10.0;
const BORDER_RADIUS_SMALL = 5.0;
const BORDER_RADIUS_CIRCLE = 50.0;

///Common Border Width
const MEDIUM_BORDER_WIDTH = 2.0;
///Icon Size
const NORMAL_ICON_SIZE = 30.0;
/// Common Paddings
const MICRO_PADDING = 5.0;
const SMALL_PADDING = 10.0;
const SMALL_PADDING_12 = 12.0;
const SMALL_PADDING_13 = 13.0;
const SMALL_PADDING_15 = 15.0;
const SMALL_PADDING_2X = 20.0;
const MEDIUM_PADDING = 30.0;
const LARGE_PADDING = 50.0;

/// Common Icon Sizes
const LARGE_ICON_SIZE =45.0;
const MEDIUM_ICON_SIZE=35.0;
const SMALL_ICON_SIZE = 15.0;
const MICRO_ICON_SIZE = 10.0;

///Text Field Size
const LARGE_TEXTFIELD_SIZE = 300.0;

/// Common Margins
const MARGIN_SMALL = 10.0;
const MARGIN_MEDIUM = 20.0;

///Widths
const MICRO_WIDTH = 5.0;
const SMALL_WIDTH = 10.0;
const MEDIUM_WIDTH = 15.0;
const LARGE_WIDTH = 20.0;
const LARGE_WIDTH2 = 25.0;
const X_WIDTH = 30.0;
const XL_WIDTH = 50.0;
const XXL_WIDTH = 40.0;
const XXXL_WIDTH = 60.0;
const KILO_WIDTH = 100.0;
const KILO_WIDTH_2X = 200.0;

///Heights
const SMALL_HEIGHT = 5.0;
const MEDIUM_HEIGHT = 10.0;
const LARGE_HEIGHT = 15.0;
const LARGE_HEIGHT2 = 25.0;
const X_HEIGHT = 30.0;
const XL_HEIGHT = 50.0;
const XXL_HEIGHT = 40.0;
const XXXL_HEIGHT = 60.0;
const XXXXL_HEIGHT = 80.0;
const KILO_HEIGHT = 100.0;
const KILO_HEIGHT_1P5 = 150.0;
const KILO_HEIGHT_2X = 200.0;

///Blur Radius
const NORMAL_BLUR_RADIUS = 10.0;
const SMALL_BLUR_RADIUS = 5.0;
///Login View
const LOGIN_VIEW_BUTTON_WIDTH = 215.0;
const SPACE_BETWEEN_ICON_AND_TITLE = 50.0;

///Location Page View
const NAVIGATION_BUTTON_HEIGHT = 50.0;
const NAVIGATION_BUTTON_WIDTH = 50.0;
const NAVIGATION_BUTTION_ICON_SIZE = 15.0;
const CITY_ICON_HEIGHT = 50.0;

const CITY_ICON_WIDTH = 90.0;

///Home Page View
const IMDB_ICON_HEIGHT = 20.0;
const IMDB_ICON_WIDTH = 32.0;
const DOT_WIDTH= 6.0;
const DOT_HEIGHT = 6.0;
const MOVIE_POSTER_HEIGHT = 279.0;
const MOVIE_POSTER_WIDTH = 171.0;
const MOVIE_VIEW_RELEASE_TAG_HEIGHT = 26.0;
const TAB_BAR_HEIGHT = 55.0;
const TAB_ITEM_WIDTH=130.0;
const MOVIE_VIEW_RELEASE_TAG_WIDTH = 24.0;

///Movie Detail Page View
const PLAY_BUTTON_ICON_SIZE = 45.0;
const MOVIE_DETAIL_POSTER_HEIGHT = 175.0;
const MOVIE_DETAIL_POSTER_WIDTH = 140.0;
const MOVIE_DETAIL_POSTER_TOP_POSITION = 210.0;
const MOVIE_DETAIL_POSTER_LEFT_POSITION = 150.0;
const MOVIE_DETAIL_SIZED_BOX_H45 = 45.0;

const MOVIE_DETAIL_REMINDER_SECTION_HEIGHT = 167.0;
const MOVIE_DETAIL_REMINDER_SECTION_WIDTH = 370.0;
const MOVIE_DETAIL_REMINDER_SECTION_REMINDER_BUTTON_HEIGHT = 35.0;
const MOVIE_DETAIL_REMINDER_SECTION_REMINDER_BUTTON_WIDTH = 150.0;
const MOVIE_DETAIL_REMINDER_SECTION_REMINDER_IMAGE_WIDTH = 86.0;
const MOVIE_DETAIL_REMINDER_SECTION_REMINDER_IMAGE_HEIGHT = 127.0;

const MOVIE_DETAIL_MOVIE_DETAIL_BOARD_CENSOR_HEIGHT = 58.0;
const MOVIE_DETAIL_MOVIE_DETAIL_BOARD_CENSOR_WIDTH = 100.0;
const MOVIE_DETAIL_MOVIE_DETAIL_BOARD_RELEASE_HEIGHT = 60.0;
const MOVIE_DETAIL_MOVIE_DETAIL_BOARD_RELEASE_WIDTH = 150.0;
const MOVIE_DETAIL_MOVIE_DETAIL_BOARD_DURATION_HEIGHT = 58.0;
const MOVIE_DETAIL_MOVIE_DETAIL_BOARD_DURATION_WIDTH = 100.0;

const MOVIE_DETAIL_POSTERVIEW_TOP_POSITION =160.0;
const MOVIE_DETAIL_POSTERVIEW_LEFT_POSITION =10.0;

const MOVIE_DETAIL_GENRE_CHIP_VIEW_HEIGHT = 26.0;
const MOVIE_DETAIL_GENRE_CHIP_VIEW_WIDTH = 63.0;

const MOVIE_DETAIL_TOP_RIGHT_ICON_TOP_POSITION = 38.0;



///Choose Time and Cinema Page
const CHOOSE_TIME_CINEMA_DAY_VIEW_TOP_CONTAINER_HEIGHT = 8.5;
const CHOOSE_TIME_CINEMA_DAY_VIEW_TOP_CONTAINER_WIDTH = 30.0;
const CHOOSE_TIME_CINEMA_DAY_VIEW_CIRCLE_CUT_HORIZONTAL = -15.0;
const CHOOSE_TIME_CINEMA_DAY_VIEW_CIRCLE_CUT_BOTTOM = 25.0;
const CHOOSE_TIME_CINEMA_DAY_VIEW_EXPANDED_SECTION_HEIGHT = 280.0;
const CHOOSE_TIME_CINEMA_POP_UP_IMAGE_VIEW_HEIGHT = 75.0;

/// Food and Beverages Page
const FOOD_AND_BEVERAGES_APP_BAR_TITLE_TEXT = "Grab a bite!";
const FOOD_AND_BEVERAGES_SKIP_BUTTON_TEXT = "SKIP";
const FOOD_AND_BEVERAGES_ADD_BUTTON_TEXT = "ADD";

///Checkout Page
const CHECKOUT_PAGE_CONTINUE_BUTTON_WIDTH = 240.0;
const CHECKOUT_PAGE_TICKET_POLICY_BUTTON_WIDTH = 220.0;
const CHECKOUT_PAGE_TOTAL_AMOUNT_VIEW_MARGIN_WIDTH = 200.0;
const CHECKOUT_PAGE_FOOD_AND_QUANTITY_WIDGET_WIDTH = 16.0;
const CHECKOUT_PAGE_FOOD_AND_QUANTITY_WIDGET_HEIGHT = 16.0;
const CHECKOUT_PAGE_MOVIE_PLACE_SECTION_WIDTH = 3.0;

/// Circle Cut Dimens
const CIRCLE_CUT_RIGHT = -25.0;
const CIRCLE_CUT_LEFT = -25.0;
const CIRCLE_CUT_HEIGHT = 20.0;
const CIRCLE_CUT_WIDTH = 50.0;

///BOOKING SUCCESS PAGE
const BOOKING_SUCCESS_PAGE_IMAGE_BOTTOM_PADDING = 100.0;
