const BORDER_RADIUS_NORMAL = 10.0;
const BORDER_RADIUS_SMALL = 5.0;
const BORDER_RADIUS_CIRCLE = 50.0;

const MICRO_PADDING = 5.0;
const SMALL_PADDING = 10.0;
const SMALL_PADDING_15 = 15.0;
const SMALL_PADDING_2X = 20.0;

const LARGE_ICON_SIZE =45.0;
const MEDIUM_ICON_SIZE=35.0;
const SMALL_ICON_SIZE = 15.0;

const LARGE_TEXTFIELD_SIZE = 300.0;
const MARGIN_SMALL = 10.0;

const NORMAL_BLUR_RADIUS = 10.0;
///Login View
const LOGIN_VIEW_BUTTON_WIDTH = 215.0;
const SPACE_BETWEEN_ICON_AND_TITLE = 50.0;

///Location Page View
const NAVIGATION_BUTTON_HEIGHT = 50.0;
const NAVIGATION_BUTTON_WIDTH = 50.0;
const NAVIGATION_BUTTION_ICON_SIZE = 15.0;
const CITY_ICON_HEIGHT = 50.0;

const CITY_ICON_WIDTH = 90.0;

///Home Page View
const IMDB_ICON_HEIGHT = 20.0;
const IMDB_ICON_WIDTH = 32.0;
const DOT_WIDTH= 6.0;
const DOT_HEIGHT = 6.0;
const MOVIE_POSTER_HEIGHT = 279.0;
const MOVIE_POSTER_WIDTH = 171.0;
const MOVIE_VIEW_RELEASE_TAG_HEIGHT = 26.0;
const TAB_BAR_HEIGHT = 55.0;
const TAB_ITEM_WIDTH=130.0;
const MOVIE_VIEW_RELEASE_TAG_WIDTH = 24.0;

//Movie Detail Page View
const PLAY_BUTTON_ICON_SIZE = 45.0;
const MOVIE_DETAIL_POSTER_HEIGHT = 175.0;
const MOVIE_DETAIL_POSTER_WIDTH = 140.0;