//Hive type id
const int HIVE_TYPE_ID_SIGN_IN_RESPONSE = 1;
const int HIVE_TYPE_ID_USER_INFO_VO = 2;
const int HIVE_TYPE_ID_CITY_VO = 3;
const int HIVE_TYPE_ID_BANNER_IMAGE_VO = 4;
const int HIVE_TYPE_ID_MOVIE_VO = 5;
const int HIVE_TYPE_ID_COLLECTION_VO = 6;
const int HIVE_TYPE_ID_GENRE_VO = 7;
const int HIVE_TYPE_ID_PRODUCTION_COMPANY_VO = 8;
const int HIVE_TYPE_ID_PRODUCTION_COUNTRY_VO = 9;
const int HIVE_TYPE_ID_SPOKEN_LANGUAGE_VO = 10;
const int HIVE_TYPE_ID_CREDIT_VO = 11;
const int HIVE_TYPE_ID_BASE_ACTOR_VO = 12;
const int HIVE_TYPE_ID_ACTOR_VO = 13;
const int HIVE_TYPE_ID_TIMESLOT_VO = 14;
const int HIVE_TYPE_ID_CINEMA_BY_DATE_VO = 15;
const int HIVE_TYPE_ID_CINEMA_VO = 16;
const int HIVE_TYPE_ID_FACILITIES_VO = 17;
const int HIVE_TYPE_ID_SNACK_VO = 18;
const int HIVE_TYPE_ID_SNACK_CATEGORY_VO = 19;
const int HIVE_TYPE_ID_PAYMENT_VO = 20;
const int HIVE_TYPE_ID_CONFIG_VO = 21;
const int HIVE_TYPE_ID_CONFIG_VO_CINEMA_TIMESLOT_VO = 22;
const int HIVE_TYPE_ID_CINEMA_TIMESLOT_VO = 23;
const int HIVE_TYPE_ID_USER_INFO_PERSISTENCE_VO = 24;


//Box names
const String BOX_NAME_SIGN_IN_RESPONSE = "BOX_NAME_SIGN_IN_RESPONSE";
const String BOX_NAME_USER_INFO_VO = "BOX_NAME_USER_INFO_VO";
const String BOX_NAME_CITY_VO = "BOX_NAME_CITY_VO";
const String BOX_NAME_BANNER_IMAGE_VO = "BOX_NAME_BANNER_IMAGE_VO";
const String BOX_NAME_MOVIE_VO = "BOX_NAME_MOVIE_VO";
const String BOX_NAME_COLLECTION_VO = "BOX_NAME_COLLECTION_VO";
const String BOX_NAME_GENRE_VO = "BOX_NAME_GENRE_VO";
const String BOX_NAME_PRODUCTION_COMPANY_VO = "BOX_NAME_PRODUCTION_COMPANY_VO";
const String BOX_NAME_PRODUCTION_COUNTRY_VO = "BOX_NAME_PRODUCTION_COUNTRY_VO";
const String BOX_NAME_SPOKEN_LANGUAGE_VO = "BOX_NAME_SPOKEN_LANGUAGE_VO";
const String BOX_NAME_CREDIT_VO = "BOX_NAME_CREDIT_VO";
const String BOX_NAME_BASE_ACTOR_VO = "BOX_NAME_BASE_ACTOR_VO";
const String BOX_NAME_ACTOR_VO = "BOX_NAME_ACTOR_VO";
const String BOX_NAME_TIMESLOT_VO = "BOX_NAME_TIMESLOT_VO";
const String BOX_NAME_CINEMA_BY_DATE_VO = "BOX_NAME_CINEMA_BY_DATE_VO";
const String BOX_NAME_CINEMA_VO = "BOX_NAME_CINEMA_VO";
const String BOX_NAME_FACILITIES_VO = "BOX_NAME_FACILITIES_VO";
const String BOX_NAME_SNACK_VO = "BOX_NAME_SNACK_VO";
const String BOX_NAME_SNACK_CATEGORY_VO = "BOX_NAME_SNACK_CATEGORY_VO";
const String BOX_NAME_PAYMENT_VO = "BOX_NAME_PAYMENT_VO";
const String BOX_NAME_CONFIG_VO = "BOX_NAME_CONFIG_VO";
const String BOX_NAME_CONFIG_VO_TIMESLOT_VO = "BOX_NAME_CONFIG_VO_TIMESLOT_VO";
const String BOX_NAME_CINEMA_TIMESLOT_VO = "BOX_NAME_CINEMA_TIMESLOT_VO";
const String BOX_NAME_USER_INFO_PERSISTENCE_VO = "BOX_NAME_USER_INFO_PERSISTENCE_VO";

